# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Entry(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, _id: str=None, title: str=None, body: str=None):  # noqa: E501
        """Document - a model defined in Swagger

        :param _id: The id of this Document.  # noqa: E501
        :type _id: string
        :param title: The title of this Document.  # noqa: E501
        :type title: str
        :param body: The body of this Document.  # noqa: E501
        :type body: str
        """
        self.swagger_types = {
            '_id': str,
            'title': str,
            'body': str
        }

        self.attribute_map = {
            '_id': '_id',
            'title': 'title',
            'body': 'body'
        }

        self.__id = _id
        self._title = title
        self._body = body

    @classmethod
    def from_dict(cls, dikt) -> 'Entry':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The document of this Document.  # noqa: E501
        :rtype: Entry
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _id(self) -> str:
        """Gets the _id of this Document.


        :return: The _id of this Document.
        :rtype: str
        """
        return self.__id

    @_id.setter
    def _id(self, _id: str):
        """Sets the _id of this Document.


        :param _id: The _id of this Document.
        :type _id: str
        """

        self.__id = _id

    @property
    def title(self) -> str:
        """Gets the title of this Document.


        :return: The title of this Document.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Document.


        :param title: The title of this Document.
        :type title: str
        """

        self._title = title

    @property
    def body(self) -> str:
        """Gets the body of this Document.


        :return: The body of this Document.
        :rtype: str
        """
        return self._body

    @body.setter
    def body(self, body: str):
        """Sets the body of this Document.


        :param body: The body of this Document.
        :type body: str
        """

        self._body = body
